spring.application.name=auth

spring.profiles.active=dev

# Configurações de Conexão RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Configurações de Mensageria Customizadas
app.rabbitmq.exchange.email=email.direct.exchange
app.rabbitmq.routingkey.email=send.email.key