spring.application.name=email-service

spring.profiles.active=dev

# Configurações de Servidor SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seu-email@gmail.com
spring.mail.password=sua-senha-de-aplicativo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.from.email=seu-email@gmail.com

# Configurações de Conexão RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Configurações de Mensageria Customizadas
app.rabbitmq.queue.email=email.queue
app.rabbitmq.exchange.email=email.direct.exchange
app.rabbitmq.routingkey.email=send.email.key